### PR TITLE
Send emails for readyToFinalize, deleted, and finalized

### LINKED ISSUE #278: More emailing: Event deleted, group meeting ready to finalize
I know we don't all love emails, but I think it's appropriate in these cases

1. A group meeting is ready for finalize, email the host
2. An invite has been deleted by an invited user. Inform the origianl sender

I think this also gives good reason to create a `Do not email me.` option in the settings, which would have to be a DB entry

### PR DESCRIPTION
**Pull request by JoshuaStorm**
Closes #278 

Moved emails to a new file since that seemed appropriate.

### CODE REVIEW

**Comment by cli1209** [comment]
when testing, I'm not receiving any emails. Not sure if it's because the email sending hasn't been turned on?

**Comment by JoshuaStorm** [comment]
It is still commented.
Check the server-side `console.logs` or just uncomment that line to test.

**Comment by JoshuaStorm** [comment]
Okay I think I'm done adding more to this PR lol

**Comment by cli1209** [comment]
Not emailing when:

User cancels an outgoing invite, screenshot below
screen shot 2017-05-13 at 9 15 42 pm

User clicks the "x" in the corner on an outgoing invite

**Comment by JoshuaStorm** [comment]
@cli1209 Those should be resolved now! If you can test it tonight I'd appreciate it. Otherwise, I think I'm going to merge

**Pull request merged**
