### PR TITLE
UI issue fix with start before/after 

### LINKED ISSUE #258: All times but After=Before should be acceptable `meetRange` values
Currently the front end throws bert alerts for totally legitimate `can't meet before` and `can't meet after` such as "12am-1am". They're kinda absurd but still legitimate.

The only time we should throw an error is if Before==After. 

~~This will require a slight backend change as well, since I think I made assumptions about the time as well.~~

### PR DESCRIPTION
**Pull request by supert165**
closes #258 

Assumed backend was handled and simply changed the front end.

### CODE REVIEW

**Comment by cli1209** [comment]
This looks good to me

**Comment by supert165** [comment]
@JoshuaStorm still getting no meetable times when I set it to 8PM - 7PM

**Comment by JoshuaStorm** [comment]
@supert165 You sure you pulled the changes? Lemme triple check

**Comment by supert165** [comment]
@JoshuaStorm ahh my bad. Pulled and seems to be working

**Comment by JoshuaStorm** [comment]
Imma go ahead and merge this 👍

**Pull request merged**
